### Customers

GET http://localhost:3000/customers

### Customers by id

GET http://localhost:3000/customers

### Get all arts

GET http://localhost:3000/images

### Get all professionals

GET http://localhost:3000/professionals

### Get professionals by id

GET http://localhost:3000/professionals/3

### Post professionals

POST localhost:3000/professionals
Content-Type: application/json
User-Agent: Firefox 145

{
  "Year": 2008,
  "Title": "test",
  "Price": null,
  "Description": null,
  "Type": null,
  "Order_ID": null,
  "Rental_ID": null,
  "art_path": "/images/lautomne.jpg",
  "imageUrl": "http://localhost:3000/images/lautomne.jpg"
}

### Delete professionals by id

DELETE http://localhost:3001/professionals/2
